### ISSUE TITLE
Revise UI Design

### ISSUE THREAD

**Issue by RioCantre** [pandeyom331/Sign-Up-Form#21]
Hi! I would like to make some changes on the UI Design.

**Comment by BellatrixLestrangee** [comment]
Hi! Can i work on it?

**Comment by RioCantre** [comment]
I'm issuing this issue so I can work with it. Kindly make a different issue @BellatrixLestrangee

**Comment by pandeyom331** [comment]
@BellatrixLestrangee kindly make a different issue

**Comment by RioCantre** [comment]
@pandeyom331 Issued already solved, created a PR. Kindly labeled it accordingly.

@BellatrixLestrangee  you can make another issue if you want, I made some room for you to explore.
