### ISSUE TITLE
bug: fix the text in the header 

### ISSUE THREAD

**Issue by RoshanMhatre** [pandeyom331/Sign-Up-Form#6]
I noticed that in the header, there is extra whitespace and grammatical errors are there.
I would like to fix those issues.
Please assign this issue to me and add the Hacktoberfest label to this issue.

**Comment by pandeyom331** [comment]
Done, Go Ahead.

**Comment by RoshanMhatre** [comment]
Yup!
Could you please add the requested label to this issue.
